codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 85%
        threshold: 1

    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, changes, files"
  behavior: default
  require_changes: false

ignore:
  - "**/stellarfork/xdr/*.*"
  - "**/stellarfork/KeyPairJvmImpl.*" # we only test the jni version of ci, not the jvm fallback
  - "**/MainExecutorService.java"
  - "**/kin/backupandrestore/*.*"
  - "**/kin/backupandrestore/backup/view/*.*"
  - "**/kin/backupandrestore/restore/view/*.*"
  - "**/kin/backupandrestore/events/*.*"
  - "**/kin/backupandrestore/qr/*.*"
  - "**/kin/backupandrestore/base/*.*"
  - "**/kin/backupandrestore/utils/*.*"
  - "**/kin/backupandrestore/widget/*.*"
  - "**/Tls12SocketFactory.*"
  - "**/OkHttpChannelBuilderForcedTls12.*"
  - "**/AppUserAuthInterceptor.*"
  - "**/UserAgentInterceptor.*"
  - "**/LoggingInterceptor.*"
  - "**/UpgradeApiV4Interceptor.*"
  - "**/KinVersionInterceptor.*"
  - "**/SDKConfig.*"
  - "**/KinTestServiceImpl.*"
  - "**/KinTestServiceImplV4.*"
